import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { Platform } from 'react-native';
import { PaperQuestionContent, PrintedCopy, PrintResult } from './types';

function escapeHtml(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function questionHtml(q: PaperQuestionContent, index: number): string {
  const marks = `<span class="marks">[${q.marks} mark${q.marks === 1 ? '' : 's'}]</span>`;
  const meta =
    q.question_type === 'theoretical'
      ? '<span class="qtype">Theory</span>'
      : '<span class="qtype">MCQ</span>';
  let opts = '';
  if (q.question_type === 'mcq' && q.options.length) {
    opts =
      '<ol class="options" type="A">' +
      q.options.map((o) => `<li>${escapeHtml(o)}</li>`).join('') +
      '</ol>';
  } else {
    opts = '<div class="answer-space"></div>';
  }
  return `
    <li class="question">
      <div class="q-head">
        <span class="q-body"><b>Q${index + 1}.</b> ${escapeHtml(q.body)}</span>
        <span class="q-tags">${meta} ${marks}</span>
      </div>
      ${opts}
    </li>`;
}

/** One copy rendered as a self-contained, page-breaking section. */
function copySection(result: PrintResult, copy: PrintedCopy, qrSvgString: string): string {
  const p = result.paper;
  const header = `
    <div class="header">
      <div class="header-text">
        <div class="exam">${escapeHtml(p.exam_name || 'Examination')}</div>
        <h1>${escapeHtml(p.title)}</h1>
        <div class="sub">
          Subject: <b>${escapeHtml(p.subject)}</b> &nbsp;·&nbsp;
          Questions: <b>${p.questions.length}</b> &nbsp;·&nbsp;
          Total marks: <b>${p.total_marks}</b>
        </div>
        <div class="copyline">Copy #${copy.copy_number} of ${result.copies} &nbsp;·&nbsp; ${escapeHtml(
          result.location
        )}</div>
      </div>
      <div class="qr">
        ${qrSvgString}
        <div class="qr-cap">Scan to verify · signed</div>
      </div>
    </div>`;

  const instructions = `
    <div class="instructions">
      <b>Instructions:</b> Do not open this booklet until instructed. This copy is uniquely
      watermarked and QR-signed; its chain of custody is tracked. Any leak is traceable to this copy.
    </div>`;

  const questions =
    '<ol class="questions">' + p.questions.map((q, i) => questionHtml(q, i)).join('') + '</ol>';

  return `<section class="copy">${header}${instructions}${questions}</section>`;
}

const DOC_STYLE = `
  * { box-sizing: border-box; }
  body { font-family: 'Times New Roman', Georgia, serif; color: #111; margin: 0; padding: 32px; }
  section.copy { page-break-after: always; }
  section.copy:last-child { page-break-after: auto; }
  .header { display: flex; justify-content: space-between; align-items: flex-start;
            border-bottom: 3px double #111; padding-bottom: 12px; margin-bottom: 16px; gap: 16px; }
  .exam { text-transform: uppercase; letter-spacing: 1px; font-size: 12px; color: #444; }
  h1 { font-size: 22px; margin: 4px 0; }
  .sub { font-size: 13px; color: #222; }
  .copyline { font-size: 12px; color: #666; margin-top: 4px; }
  .qr { text-align: center; width: 130px; flex: none; }
  .qr svg { width: 120px; height: 120px; }
  .qr-cap { font-size: 9px; color: #666; margin-top: 2px; }
  .instructions { font-size: 12px; background: #f4f4f4; border: 1px solid #ddd;
                  padding: 8px 12px; border-radius: 6px; margin-bottom: 18px; }
  ol.questions { padding-left: 0; list-style: none; counter-reset: q; }
  li.question { margin-bottom: 18px; page-break-inside: avoid; }
  .q-head { display: flex; justify-content: space-between; gap: 12px; align-items: baseline; }
  .q-body { font-size: 14px; line-height: 1.5; }
  .q-tags { white-space: nowrap; }
  .qtype { font-size: 9px; text-transform: uppercase; letter-spacing: .5px; color: #fff;
           background: #2f6bf6; padding: 1px 6px; border-radius: 999px; }
  .marks { font-size: 11px; color: #444; }
  ol.options { margin: 8px 0 0 18px; }
  ol.options li { font-size: 13px; line-height: 1.6; }
  .answer-space { height: 70px; border-bottom: 1px dashed #bbb; margin-top: 8px; }
  @media print { body { padding: 12mm; } .question { page-break-inside: avoid; } }`;

function htmlDoc(title: string, body: string): string {
  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
<style>${DOC_STYLE}</style>
</head>
<body>${body}</body>
</html>`;
}

/**
 * Build a printable A4 question paper for a single copy. The signed QR is
 * embedded inline (the SVG is generated by the caller via qrSvg()).
 */
export function buildPaperHtml(result: PrintResult, copy: PrintedCopy, qrSvgString: string): string {
  return htmlDoc(
    `${result.paper.title} — Copy #${copy.copy_number}`,
    copySection(result, copy, qrSvgString)
  );
}

/**
 * Build ONE document containing every copy, each on its own page(s) with its
 * own signed QR. `copies` pairs each printed copy with its pre-rendered QR SVG.
 */
export function buildAllCopiesHtml(
  result: PrintResult,
  copies: { copy: PrintedCopy; qrSvg: string }[]
): string {
  const body = copies.map(({ copy, qrSvg }) => copySection(result, copy, qrSvg)).join('');
  return htmlDoc(`${result.paper.title} — ${copies.length} copies`, body);
}

/** Print an HTML document. Web uses a hidden iframe; native uses expo-print. */
export async function printHtml(html: string): Promise<void> {
  if (Platform.OS === 'web') {
    const iframe = document.createElement('iframe');
    iframe.style.cssText = 'position:fixed;right:0;bottom:0;width:0;height:0;border:0;';
    document.body.appendChild(iframe);
    const doc = iframe.contentWindow?.document;
    if (!doc) return;
    doc.open();
    doc.write(html);
    doc.close();
    const win = iframe.contentWindow;
    const cleanup = () => setTimeout(() => iframe.remove(), 1000);
    win?.addEventListener('afterprint', cleanup);
    setTimeout(() => {
      win?.focus();
      win?.print();
    }, 300);
    return;
  }
  await Print.printAsync({ html });
}

/** Native-only: render to a PDF file and open the share sheet. */
export async function sharePaperPdf(html: string): Promise<void> {
  if (Platform.OS === 'web') {
    await printHtml(html);
    return;
  }
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf' });
  }
}
